remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Alexandria Future
description: This is where I share cool stuff about my life
author: Samanta Rodrigues
